server:
  port: 9090

logging:
  # ROOT레벨 전체 로깅 레벨 결정
  level:
    root: error

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aehae.synology.me:3306/muggi-market
    username: muggi
    password: DontDreamBeIt!


  jpa: #JPA 설정
    properties:
      hibernate:
        #방언 설정
        dialect: org.hibernate.dialect.MariaDBDialect
        #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
        show_sql: true
        #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
        format_sql: true
        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
        use_sql_comments: true

  thymeleaf:
    #파일 수정시 반영하려면 하면 재시작을 해줘야 한다. 브라우저 새로고침시 수정사항 반영을 취해 cache=false 설정(운영시 true)
    cache: false
    check-template-location: true

